version: 1.0.{build}
environment:
  JAVA_HOME: C:\Program Files (x86)\Java\jdk1.7.0\
install:
- cinst maven
- set PATH=C:\bin\apache-maven-3.3.3\bin;%JAVA_HOME%\bin;%PATH%
cache:
- C:\bin\apache-maven-3.3.3
- C:\Users\appveyor\.m2
build_script:
- mvn clean package assembly:directory
test_script:
- mvn test
